### ISSUE TITLE
ReadOnlyArray causes a compilation error when a coverage or profiler reporter is defined

### ISSUE THREAD

**Issue by Aidan63** [AlexHaxe/haxe-instrument#1]
Hello,
Tried to get some coverage reporting going with my existing project but ran into some issues where `haxe.ds.ReadOnlyArray` is used, the below sample will not compile with haxe 4.1.3.

Main.hx
```haxe
package tests;

import haxe.ds.ReadOnlyArray;

class Main {
	static function main() {
		final array = [ 'hello', 'world' ];

		func(array);
	}

	static function func(_array : ReadOnlyArray<String>) {
		trace(_array.length);
	}
}
```
build.hxml
```
-cp src
-L instrument
-D coverage-console-summary-reporter
-main tests.Main
--macro instrument.Instrumentation.coverage(['tests'], ['src'], [])
--interp
```
With the directory structure being `src/test/Main.hx`. Trying to compile this I get the following error.

```Instrumenting .C:\Users\AidanLee\AppData\Roaming/haxe/versions/4.1.3/std/haxe/ds/ReadOnlyArray.hx:34: characters 54-65 : You can only declare from/to with compatible types```

Once I remove the the coverage console define everything compiles and runs fine.

**Comment by AlexHaxe** [comment]
thanks for reporting, should be fixed in latest git version
